### ISSUE TITLE
其他主机访问主题失效

### ISSUE THREAD

**Issue by changzl132** [MoeOxygen/halo-theme-fantasy#1]
我用这个主题搭建了一个博客，但是当我用其他主机访问时主题失效了。当我切换为其他主题时，发现并没有这个问题。

**Comment by MoeOxygen** [comment]
是使用ip访问的吗? head标签中含有`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
去掉后应该就可以正常请求css了

**Comment by changzl132** [comment]
> 是使用ip访问的吗? head标签中含有`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` 去掉后应该就可以正常请求css了


> 是使用ip访问的吗? head标签中含有`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` 去掉后应该就可以正常请求css了

当我尝试在压缩包里面去掉这行代码时提示没有权限，只好解压删除header文件里面的这行代码，重新压缩一下，与原文件名一样，但提示上传错误。无奈尝试用原压缩包上传，在搭好博客之后，用win的web开发者工具消除这行代码，但仍然是只有本机访问有样式，其他主机访问没有样式

**Comment by MoeOxygen** [comment]
尝试在 Halo后台 - 外观 - 主题编辑 中删除
