### ISSUE TITLE
首页在点击搜索后点击其他功能无效

### ISSUE THREAD

**Issue by hahago2026** [MoeOxygen/halo-theme-fantasy#2]
首页在点击搜索按钮后，在显示搜索框的时候点击其他功能如首页、归档、关于本页都无法返回，只能再次点击搜索按钮取消搜索框才能正常点击首页等功能按钮

**Comment by MoeOxygen** [comment]
> 首页在点击搜索按钮后，在显示搜索框的时候点击其他功能如首页、归档、关于本页都无法返回，只能再次点击搜索按钮取消搜索框才能正常点击首页等功能按钮

原主题好像也是这样，没有做修改
