### ISSUE TITLE
主题导入异常

### ISSUE THREAD

**Issue by kanon-H** [MoeOxygen/halo-theme-fantasy#3]
![image](https://user-images.githubusercontent.com/108659129/222913707-43e59310-1436-492d-9b24-d189315604f4.png)

![image](https://user-images.githubusercontent.com/108659129/222913727-97773e30-ad23-4865-9633-470dd6f65fe1.png)

您好，2.0主题导入时显示异常，并且预览没有静态资源，请问是我哪里操作有问题，需要如何处理

**Comment by kanon-H** [comment]
尝试了主题下载里的两个包都不行呢，麻烦给看下

**Comment by MoeOxygen** [comment]
版本是 2.几 ?

**Comment by kanon-H** [comment]
> 版本是 2.几 ?

是最新的2.3.0

**Comment by MoeOxygen** [comment]
> > 版本是 2.几 ?
> 
> 是最新的2.3.0

把 `layout.html`里的

```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
```
删掉
