### ISSUE TITLE
latex 语法

### ISSUE THREAD

**Issue by qyzhizi** [MoeOxygen/halo-theme-fantasy#4]
latex 语法渲染应该在主题中支持还是应该在halo的js中得到支持？

**Comment by MoeOxygen** [comment]
由于主题没有内置latex或mathjax的js, 所以请在halo后台 - 自定义全局head中添加

**Comment by qyzhizi** [comment]
> 由于主题没有内置latex或mathjax的js, 所以请在halo后台 - 自定义全局head中添加

好的
